#!/bin/bash
# chkconfig:   - 90 15

. /etc/rc.d/init.d/functions

NAME=uWSGI
EXEC=/usr/bin/uwsgi
ARGS="--yaml /etc/uwsgi.yaml"
LOCK_FILE=/var/lock/subsys/uwsgi

start() {
  echo -n "Starting $NAME: "
  daemon $EXEC $ARGS
  retval=$?
  echo
  [ $retval -eq 0 ] && touch $LOCK_FILE
  return $retval
}

stop() {
  echo -n "Stopping $NAME: "
  killproc $EXEC
  retval=$?
  echo
  [ $retval -eq 0 ] && rm -f $LOCK_FILE
  return $retval
}

reload() {
  echo "Reloading $NAME"
  killproc $EXEC -HUP
  RETVAL=$?
  echo
}

restart() {
  stop
  start
}

rh_status() {
  status $EXEC
}

rh_status_q() {
  rh_status >/dev/null 2>&1
}

case "$1" in
  start)
    if ! pidof $EXEC >/dev/null; then
        rh_status_q && exit 0
        $1
    else
        echo -e "\n$NAME is already started...\n"
    fi
    ;;
  stop)
    if pidof $EXEC >/dev/null; then
        rh_status_q || exit 0
        $1
    else
        echo -e "\n$NAME can not be stoped because its not running...\n"
    fi
    ;;
  restart|force-reload)
    $1
    ;;
  reload)
    rh_status_q || exit 7
    $1
    ;;
  status)
    rh_status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload|status}" >&2
    exit 2
    ;;
esac
exit 0